# Generated by Django 6.1.1 on 2026-09-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_name_doctor_username_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Professional Experience & Bio'),
        ),
    ]
