# Generated by Django 6.1.1 on 2026-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Doctor Comments'),
        ),
    ]
