# Generated by Django 6.1.1 on 2026-09-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_doctor_doctor_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_comments',
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Doctor Comments'),
        ),
    ]
